name: aviastil
description: Літайте на таксі, замовляйте на столі!

publish_to: 'none'

version: 0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
    
  firebase_core: "0.5.3"
  firebase_analytics: ^6.3.0

  smart_select: ^4.3.2
  rflutter_alert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true